# Generated by Django 4.1.1 on 2022-10-19 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(editable=False, max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9981234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('date_of_birth', models.DateField()),
                ('rank', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('wallet', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
