# Generated by Django 4.1.1 on 2022-10-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='tutorialtype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='rank',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes number'),
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('checking', models.BooleanField(default=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.task')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
