# Generated by Django 4.1.1 on 2022-10-21 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0002_alter_comment_options_alter_tutorialtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tutorial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial', verbose_name='Tutorial'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tutorial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial', verbose_name='Tutorial'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tutorial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial', verbose_name='Tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('id', 'user_id')},
        ),
    ]
